dbt_learn_repos:
  outputs:
    dev:
      account: IFBNHLP-ATB70813
      database: RAW
      schema : STAGING
      password: Sainathsc@1234
      role: ACCOUNTADMIN
      threads: 1
      type: snowflake
      user: saichakrawar120
      warehouse: COMPUTE_WH
  target: dev
